name: setting_sm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^2.0.0
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.6.2

flutter:
  generate: true # Tambahkan baris ini
  uses-material-design: true

  assets:
    - assets/img/
