// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4P5_uy1xVyVVkhsJgH7ddgg23yEZIpM',
    appId: '1:253157680467:web:ce9099445f7a2c5566eda6',
    messagingSenderId: '253157680467',
    projectId: 'settings-ppb-c68d1',
    authDomain: 'settings-ppb-c68d1.firebaseapp.com',
    storageBucket: 'settings-ppb-c68d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvlbpxzV7hh6Hd1cYslstwYU1EPE8QYiM',
    appId: '1:253157680467:android:16934626b1b00dc666eda6',
    messagingSenderId: '253157680467',
    projectId: 'settings-ppb-c68d1',
    storageBucket: 'settings-ppb-c68d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7d6uqXG_7Bcb2X_qgfcxwqX-d-p0p0M',
    appId: '1:253157680467:ios:dcd1ce58e6c1953266eda6',
    messagingSenderId: '253157680467',
    projectId: 'settings-ppb-c68d1',
    storageBucket: 'settings-ppb-c68d1.appspot.com',
    iosBundleId: 'com.example.settingSm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7d6uqXG_7Bcb2X_qgfcxwqX-d-p0p0M',
    appId: '1:253157680467:ios:dcd1ce58e6c1953266eda6',
    messagingSenderId: '253157680467',
    projectId: 'settings-ppb-c68d1',
    storageBucket: 'settings-ppb-c68d1.appspot.com',
    iosBundleId: 'com.example.settingSm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM4P5_uy1xVyVVkhsJgH7ddgg23yEZIpM',
    appId: '1:253157680467:web:fc336ee8949d1cca66eda6',
    messagingSenderId: '253157680467',
    projectId: 'settings-ppb-c68d1',
    authDomain: 'settings-ppb-c68d1.firebaseapp.com',
    storageBucket: 'settings-ppb-c68d1.appspot.com',
  );
}
